package com.xiaomai.geek.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARTICLE_RECORD".
*/
public class ArticleRecordDao extends AbstractDao<ArticleRecord, Long> {

    public static final String TABLENAME = "ARTICLE_RECORD";

    /**
     * Properties of entity ArticleRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Author = new Property(3, String.class, "author", false, "AUTHOR");
        public final static Property Keywords = new Property(4, String.class, "keywords", false, "KEYWORDS");
        public final static Property ReadTime = new Property(5, long.class, "readTime", false, "READ_TIME");
        public final static Property Times = new Property(6, int.class, "times", false, "TIMES");
        public final static Property Progress = new Property(7, float.class, "progress", false, "PROGRESS");
    }


    public ArticleRecordDao(DaoConfig config) {
        super(config);
    }
    
    public ArticleRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARTICLE_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"URL\" TEXT UNIQUE ," + // 1: url
                "\"NAME\" TEXT," + // 2: name
                "\"AUTHOR\" TEXT," + // 3: author
                "\"KEYWORDS\" TEXT," + // 4: keywords
                "\"READ_TIME\" INTEGER NOT NULL ," + // 5: readTime
                "\"TIMES\" INTEGER NOT NULL ," + // 6: times
                "\"PROGRESS\" REAL NOT NULL );"); // 7: progress
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARTICLE_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ArticleRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
 
        String keywords = entity.getKeywords();
        if (keywords != null) {
            stmt.bindString(5, keywords);
        }
        stmt.bindLong(6, entity.getReadTime());
        stmt.bindLong(7, entity.getTimes());
        stmt.bindDouble(8, entity.getProgress());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ArticleRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(2, url);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
 
        String keywords = entity.getKeywords();
        if (keywords != null) {
            stmt.bindString(5, keywords);
        }
        stmt.bindLong(6, entity.getReadTime());
        stmt.bindLong(7, entity.getTimes());
        stmt.bindDouble(8, entity.getProgress());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ArticleRecord readEntity(Cursor cursor, int offset) {
        ArticleRecord entity = new ArticleRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // url
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // author
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // keywords
            cursor.getLong(offset + 5), // readTime
            cursor.getInt(offset + 6), // times
            cursor.getFloat(offset + 7) // progress
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ArticleRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAuthor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setKeywords(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setReadTime(cursor.getLong(offset + 5));
        entity.setTimes(cursor.getInt(offset + 6));
        entity.setProgress(cursor.getFloat(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ArticleRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ArticleRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ArticleRecord entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
