package com.xiaomai.geek.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xiaomai.geek.db.Article;
import com.xiaomai.geek.db.ArticleCategory;
import com.xiaomai.geek.db.Config;

import com.xiaomai.geek.db.ArticleDao;
import com.xiaomai.geek.db.ArticleCategoryDao;
import com.xiaomai.geek.db.ConfigDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDaoConfig;
    private final DaoConfig articleCategoryDaoConfig;
    private final DaoConfig configDaoConfig;

    private final ArticleDao articleDao;
    private final ArticleCategoryDao articleCategoryDao;
    private final ConfigDao configDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        articleCategoryDaoConfig = daoConfigMap.get(ArticleCategoryDao.class).clone();
        articleCategoryDaoConfig.initIdentityScope(type);

        configDaoConfig = daoConfigMap.get(ConfigDao.class).clone();
        configDaoConfig.initIdentityScope(type);

        articleDao = new ArticleDao(articleDaoConfig, this);
        articleCategoryDao = new ArticleCategoryDao(articleCategoryDaoConfig, this);
        configDao = new ConfigDao(configDaoConfig, this);

        registerDao(Article.class, articleDao);
        registerDao(ArticleCategory.class, articleCategoryDao);
        registerDao(Config.class, configDao);
    }
    
    public void clear() {
        articleDaoConfig.clearIdentityScope();
        articleCategoryDaoConfig.clearIdentityScope();
        configDaoConfig.clearIdentityScope();
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public ArticleCategoryDao getArticleCategoryDao() {
        return articleCategoryDao;
    }

    public ConfigDao getConfigDao() {
        return configDao;
    }

}
